# This configuration file defines Network Environment for a
# Baremetal Deployment of OPNFV. It contains default values
# for 4 following networks:
#
# - admin
# - private*
# - public
# - storage*
#
# *) optional networks
#
# Any values missing from this configuration file will be
# auto-detected by deployment script from the existing network
# configuration of the jumphost.
#
# Optional networks will be consolidated with the admin network
# if not explicitely configured.
#
# See short description of the networks in the comments below.
#

# "admin" is the short name for Control Plane Network.
# During OPNFV deployment it is used for node provisioning so
# PXE boot should be enabled for the related interfaces on all
# the nodes in the OPNFV cluster. After the deployment this
# network is used as the OpenStack management network which
# carries e.g. communication between its internal components.
#
admin_network:
  enabled: true
  network_type: bridged
  bridged_interface: ''
  bond_interfaces: ''
  usable_ip_range: 192.0.2.11,192.0.2.99
  gateway: 192.0.2.1
  provisioner_ip: 192.0.2.1
  cidr: 192.0.2.0/24
  dhcp_range: 192.0.2.2,192.0.2.10
  introspection_range: 192.0.2.100,192.0.2.120

# "private" is an optional network used as underlying physical
# network for virtual provider and tenant networks created by
# users. Traffic between virtual machines is carried by this
# network.
#
private_network:
  enabled: true
  vlan: 400
  cidr: 11.0.0.0/24

# "public" network is used for external connectivity.
# The external network provides Internet access for virtual
# machines. If floating IP range is defined for this network,
# floating IP addresses can be used for accessing virtual
# machines from outside of OPNFV cluster. Also external REST
# API calls use this network.
#
public_network:
  enabled: true
  network_type: ''
  bridged_interface: ''
  vlan: 500
  cidr: 192.168.37.0/24
  gateway: 192.168.37.1
  floating_ip_range: 192.168.37.200,192.168.37.220
  usable_ip_range: 192.168.37.10,192.168.37.199
  provisioner_ip: 192.168.37.1

# "storage" is an optional network used by storage backends.
# You can configure this network in order to reduce load on
# Control Plane Network.
#
storage_network:
  enabled: true
  vlan: 200
  cidr: 12.0.0.0/24
