global_params:
  ha_enabled: false

deploy_options:
  sdn_controller: false
  sdn_l3: false
  tacker: true
  congress: true
  sfc: false
  vpn: false
  dataplane: ovs_dpdk
  performance:
    Controller:
      kernel:
        hugepagesz: 2M
        hugepages: 1024
    Compute:
      nova:
        libvirtpin: 1
      kernel:
        hugepagesz: 2M
        hugepages: 1024
        intel_iommu: 'on'
        iommu: pt
