global_params:
  ha_enabled: true

deploy_options:
  sdn_controller: false
  sdn_l3: false
  tacker: false
  congress: false
  sfc: false
  vpn: false
  performance:
    Controller:
      isolcpus: 1
      hugepage: 2M
    Compute:
      isolcpus: 0
      libvirtpin: 1
      hugepage: 2M
