---
global_params:
  ha_enabled: false
  patches:
    undercloud:
      - change-id: I301370fbf47a71291614dd60e4c64adc7b5ebb42
        project: openstack/tripleo-heat-templates
deploy_options:
  os_version: pike
  sdn_controller: false
  tacker: false
  congress: false
  sfc: false
  vpn: false
