global_params:
  ha_enabled: false

deploy_options:
  sdn_controller: opendaylight
  sdn_l3: false
  tacker: false
  congress: false
  sfc: false
  vpn: false
  dataplane: ovs_dpdk
  performance:
    Controller:
      kernel:
        hugepage: 2M
    Compute:
      nova:
        libvirtpin: 1
      kernel:
        default_hugepagesz: 2M
        hugepagesz: 2M
        hugepages: 128
        intel_iommu: 'on'
        iommu: pt
