---
global_params:
  ha_enabled: true

deploy_options:
  containers: true
  os_version: master
  sdn_controller: opendaylight
  odl_version: master
  tacker: true
  congress: false
  sfc: true
  vpn: false