global_params:
  ha_enabled: false

deploy_options:
  sdn_controller: opendaylight
  sdn_l3: false
  odl_version: carbon
  tacker: false
  congress: true
  sfc: false
  vpn: false
  l2gw_sriov: true
  sriov_iface: em2
