---
global_params:
  ha_enabled: false
  patches:
    overcloud:
      - change-id: Ie988ba6a2d444a614e97c0edf5fce24b23970310
        project: openstack/puppet-tripleo
        branch: stable/queens
deploy_options:
  containers: true
  os_version: queens
  sdn_controller: opendaylight
  odl_version: oxygen
  tacker: false
  congress: false
  sfc: false
  vpn: false
